/*
    heroku config:add FACEBOOK_APP_ID=FACEBOOK_APP_ID_XXX
    heroku config:add FACEBOOK_APP_SECRET=FACEBOOK_APP_SECRET_XXX
    heroku config:add WEB_SITE_URI=WEB_SITE_URI_XXX
 */

module.exports = {
    FACEBOOK_APP_ID: "FACEBOOK_APP_ID_XXX",
    FACEBOOK_APP_SECRET: "FACEBOOK_APP_SECRET_XXX",
    WEB_SITE_URI: "WEB_SITE_URI_XXX"